### ISSUE TITLE
Erros Do Módulo

### ISSUE THREAD

**Issue by PauloPeres** [payu-br/bcash-magento-transparente#49]
Olá sou Paulo Parceiro da Bcash pela IcozWeb.
Estavamos revendo o Módulo do Bcash e verificamos alguns problemas.

Primeiro, no Arquivo 
lib>BcashApi>src>Http>Connection.php lá para as linhas 82
As respostas de erro do magento vem em XML não em JSON, entào quando vocês estão tentando salvar algum log esta vindo vazio.
Como é só log eu troquei para salvar a resposta de erro Crua.
```
if ($response->isBadRequest()) {
	throw new ValidationException($response->getContent());
}

throw new ConnectionException($response->getContent(), curl_error($ch));
```

Outro Problema... E esse na verdade é uma melhoria, a API do Bcash vem com um Autoloader só que o Magento também tem o Autoloader dele, então quando vocês usam o comando de inversão por exemplo
```
use Bcash\Http\PostRequest;
use Bcash\Http\Response;
use Bcash\Helper\HttpHelper;
use Bcash\Exception\ValidationException;
use Bcash\Exception\ConnectionException;
```
Apesar do arquivo estar sendo inserido, esta causando um warning de tentativa de insersão pelo Autoloader do Varien, vocês podem verificar o Warning no system.log
É bom tentar arrumar isso, pois teoricamente isso diminui a velocidade das requisições, talvez mudificar os arquivos para sempre inserir os arquivos usando o Autoloader do Varien. Ou algo do tipo...

E mais uma coisa, seria legal colocar no caso de Erro de autenticação no Checkout, para o usuario final conseguir entender se ele configurou o Bcash Erroniamente, ou se precisa liberar alguma coisa pelo lado da Bcash em si.

Obrigado
Paulo Peres Jr
Equipe IcozWeb

**Comment by viniciustaveira** [comment]
Olá Paulo, muito obrigado por dedicar um tempo para retornar esses problemas do módulo, é de grande ajuda para evoluí-lo.

A dica que você deu do Varien ajudou resolver o problema dos warnings. Já aplicamos as melhorias e está em validação no branch Develop, logo será disponibilizado no Master deste repositório.

Sobre problemas no retorno da API, está sendo tratado neste repositório: https://github.com/payu-br/bcash-php-sdk

Valeu. Abraço.

**Comment by PauloPeres** [comment]
Olá Vinicius.
Baixei aqui e esta bem melhor.
Mas ainda existe um "erro" de omição de erro para o usuario.
Veja bem o arquivo app/core/Mage/Checkout/controller/OnePageController.php (do proprio magento) por volta da linha 586 tem esse código
```
catch (Mage_Payment_Model_Info_Exception $e) {
            $message = $e->getMessage();
            if (!empty($message)) {
                $result['error_messages'] = $message;
            }
            $result['goto_section'] = 'payment';
            $result['update_section'] = array(
                'name' => 'payment-method',
                'html' => $this->_getPaymentMethodsHtml()
            );
}
```
Mas o opt_checkout do magento só da alerta em erro quando o 
```
$result['success'] = false;
$result['error'] = true;
```
Acho que é um método de supressão de erros deles quando é Mage_Payment_Model_Info_Exception

Uma solução bem rápida assim o usuário final conseguiria ver algum erro que aconteceu no processo de compra agilizando assim qualquer arrumação seria trocar os Exceptions que vocês estão mandando nos initialize de cada método de pagamento 
Model/Bankslip.php
Model/Creditcard.php
Model/Onlinetransfer.php
trocar o Exceptions de Mage_Payment_Model_Info_Exception para Mage_Core_Exception dessa maneira o método de pagamento não vai oprimir os erros e o cliente vai conseguir saber se configurou as coisas corretas (ou esta comprando com o mesmo email do vendedor)

Outro problema é no seus forms e o css
Quando a pagina de Pagamento esta para ser escolhida já aparece o método do pagamento por que por default todo o conteudo do seu form deveria estar dentro do 
<div class="form-list" id="payment_form_<?php echo $code; ?>" style="display:none;">

E tem algums classes que vocês copiaram do bootstrap (label e algumas outras) que pode acabar alterando o css de outros módulos de pagemento.

Overall great job...
Já fiz todas essas alteraçãoes se vocês querem acesso só dar um toque.

**Comment by viniciustaveira** [comment]
Agradeço novamente o retorno Paulo.

Se não me engano, o Mage_Payment_Model_Info_Exception foi usado para retornar na tela de pagamento caso houver algum problema, por exemplo: no One Page Checkout, no momento de concluir o Order Review se ocorrer algum erro na criação de transação Bcash o usuário será retornado para a tela (etapa) de Pagamento ao invés de permanecer no Order Review. 
Sobre o conteúdo do Form vamos considerar esses ajustes.

Obrigado pelo reconhecimento! Valeu!

**Comment by PauloPeres** [comment]
Opa Vinicius. Até entendo essa parada de voltar par ao método de pagamento.. (no nosso casa nós tiramos o ultimo passo do processo), mas então de qualquer maneira precisamos mostrar um feedback para o usuário, o por que falhou o pagamento dele, as vezes ele.

Outra coisa, alguns clientes que já estavam usando o módulo antigo tiveram problemas com pedidos já criados no módulo antigo.. não sei quantas pessoas estão usando o módulo, mas tivemos que fazer um update no seu módulo novo para que ele desse update nas orders antigas e dessa maneira não causar erro na hora de ver as orders antigas.
Segue o Erro: 
 ```
a:5:{i:0;s:55:"A forma de pagamento solicitada não está disponível.";i:1;s:6295:"#0 /app/code/core/Mage/Payment/Model/Info.php(82): Mage::throwException('A forma de paga...')
```
Segue o Fix no update criando um arquivo novo no sql chamado mysql4-upgrade-1.2.0-1.2.1.php
```
<?php
// Updating because of the old payment method
// UPDATE`sales_flat_order_payment` SET `method`= 'bcash_creditcard'  WHERE `method` = 'pagamento';
try {
    $installer = $this;
    $installer->startSetup();
    $installer->run("UPDATE `sales_flat_order_payment` SET `method`= 'bcash_creditcard'  WHERE `method` = 'pagamento';");
    $installer->endSetup();
} catch (Exception $e) {
    Mage::helper("bcash")->saveLog("Exception - sql/pagamento_setup/mysql4-upgrade-1.2.0-1.2.1.php: " . $e->getMessage());
}
```
E obviamente mudar o config dos modulos para versão 1.2.1


E outra perguntinha :D aproveitando que já estou aqui...
Vocês tem algum plano de fazer o método de pagamento de vocês funcionar no painel administrativo? Temos varios clientes que fazem venda por telefone e adoraria completar a venda pelo painel administrativo, vejo que o módulo de vocês esta quase completo para essa parte funcionar, falta só alguns arquivos, queria saber se o processo de segurança do Bcash deixaria isso acontecer (por causa de multiplas vendas saindo de mesmo IP, e coisa to tipo)

Anyway Keep up the good work!

Vlw abraços.

**Comment by viniciustaveira** [comment]
Olá Paulo. Obrigado mais uma vez pelo retorno.

A opção do lojista realizar a venda pelo painel administrativo é interessante, pode ser pensado como uma nova feature sim, repassei para o pessoal.

Sobre a atualização de pedidos realizados no módulo antigo realmente não havia sido tratado, fiz um commit referenciando esta issue se você quiser conferir. Foi feita a correção tratando se o pedido antigo foi utilizando o meio por Boleto, Cartão ou TEF e aplicando o nome do método correspondente, ficou assim:

```
$installer = $this;
    $installer->startSetup();
    $table_order_payment = $installer->getTable('sales_flat_order_payment');
    $table_order = $installer->getTable('sales_flat_order');
    $table_quote_payment = $installer->getTable('sales_flat_quote_payment');
    $table_quote = $installer->getTable('sales_flat_quote');
    // Payment method codes
    $credit_card = "(1, 2, 37, 45, 55, 56, 63)";
    $bankslip = "10";
    $onlinetransfer = "(58, 59, 60, 61, 62)";
    $installer->run("
        UPDATE `{$table_order_payment}`
            SET `method` = 'bcash_creditcard'
            WHERE `parent_id` IN
                (SELECT `entity_id` FROM `{$table_order}`
                    WHERE `payment_method_bcash` IN {$credit_card}
                 );
        UPDATE `{$table_order_payment}`
            SET `method` = 'bcash_bankslip'
            WHERE `parent_id` IN
                (SELECT `entity_id` FROM `{$table_order}`
                    WHERE `payment_method_bcash` = {$bankslip}
                 );
        UPDATE `{$table_order_payment}`
            SET `method` = 'bcash_onlinetransfer'
            WHERE `parent_id` IN
                (SELECT `entity_id` FROM `{$table_order}`
                    WHERE `payment_method_bcash` IN {$onlinetransfer}
                 );
        UPDATE `{$table_quote_payment}`
            SET `method` = 'bcash_creditcard'
            WHERE `quote_id` IN
                (SELECT `entity_id` FROM `{$table_quote}`
                    WHERE `payment_method_bcash` IN {$credit_card}
                 );
        UPDATE `{$table_quote_payment}`
            SET `method` = 'bcash_bankslip'
            WHERE `quote_id` IN
                (SELECT `entity_id` FROM `{$table_quote}`
                    WHERE `payment_method_bcash` = {$bankslip}
                 );
        UPDATE `{$table_quote_payment}`
            SET `method` = 'bcash_onlinetransfer'
            WHERE `quote_id` IN
                (SELECT `entity_id` FROM `{$table_quote}`
                    WHERE `payment_method_bcash` IN {$onlinetransfer}
                 );
    ");
    $installer->endSetup();

```
