### ISSUE TITLE
Não substituir a pasta?

### ISSUE THREAD

**Issue by pdroaugust** [payu-br/bcash-magento-transparente#57]
É para não substituir a pasta ou o arquivo?

**Comment by viniciustaveira** [comment]
Olá @pdroaugust ,

Sobre o item 1 da instalação manual:
"Copie as pastas app, skin, e lib para o diretório de instalação do Magento sem substituir as pastas já existentes."

Não devem ser substituídas as pastas e arquivos existentes na sua loja Magento, deve-se fazer a **ação de mesclagem** com as pastas do módulo.

Além do processo manual, você tem a opção de realizar a instalação através do Magento Connect pelo package (.tgz) mais recente contido neste repositório ou também agora através do link disponível: https://www.magentocommerce.com/magento-connect/bcash-pagamento-transparente.html

Abraço.
