### ISSUE TITLE
Instalei a versão 1.2.2 e não consigo verificar os pedidos anteriores

### ISSUE THREAD

**Issue by pdroaugust** [payu-br/bcash-magento-transparente#61]
Depois de instalado a versão 1.2.2 do módulo, não é possível visualizar os pedidos que já estavam feitos. Porém, os pedidos feitos agora estão funcionado normalmente. Alguma sugestão?

![screenshot_1](https://cloud.githubusercontent.com/assets/9399821/12521420/bba2d79a-c131-11e5-939a-8150238f10d8.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/9399821/12521434/d20096a8-c131-11e5-9976-e00e28770168.png)

**Comment by viniciustaveira** [comment]
@pdroaugust , verifique por favor se o procedimento do arquivo abaixo foi executado corretamente.

https://github.com/payu-br/bcash-magento-transparente/blob/master/app/code/community/Bcash/Pagamento/sql/pagamento_setup/mysql4-upgrade-0.1.0-1.2.2.php

**Comment by pdroaugust** [comment]
Verifiquei que o arquivo está no local. Limpei o cache e mesmo assim não funcionou.

**Comment by viniciustaveira** [comment]
Ao executar o comando abaixo qual versão é retornada? (caso utilizar prefixo, renomeie a tabela)

```
SELECT * FROM `core_resource` WHERE `code` = 'pagamento_setup';
```

Se retornar a versão 1.2.2... significa que houve algum problema na execução do script, você pode consultar o log para mais detalhes.

Para corrigir e executar o script corretamente, aconselho fazer o seguinte:

- Atualize a versão de setup através do comando:
```
UPDATE `core_resource` SET `version` = '0.1.0', `data_version` = '0.1.0' WHERE `code` = 'pagamento_setup';
```
- Atualize a indexação dos arquivos em System > Index Management selecionando todos;
- Atualize o cache em System > Cache Management.

Caso ainda tiver problemas:

- Remova a referência do setup através do comando:
```
DELETE FROM `core_resource` WHERE `code` = 'pagamento_setup';
```
- Renomeie o arquivo **mysql4-upgrade-0.1.0-1.2.2.php** para **mysql4-upgrade-0.1.0-1.2.3.php**
- Atualize a indexação dos arquivos em System > Index Management
- Atualize o cache em System > Cache Management.

**Comment by pdroaugust** [comment]
Resolvido.
