### ISSUE TITLE
Erro ao cancelar

### ISSUE THREAD

**Issue by PauloPeres** [payu-br/bcash-magento-transparente#64]
Olá, tive um problema em um cliente agora de pouco, que bagunçou bastante o status de um pedido.

Aconteceu o seguinte, o cliente fez pedido, foi cancelado pelo bcash, minutos depois foi aprovado pelo Bcash.

Bcash criou Fatura sem produto, e mudou status do pedido para completo, agora não consigo gerar o envio, e ao imprimir a fatura não mostra o descritivo dos pedidos.

Por favor olhar nesse detalhes.

**Comment by ftgouveia** [comment]
Olá Paulo,

Obrigado pelo contato, realizamos a correção deste problema e se encontra disponível na release 1.2.4.

Qualquer problema, não hesite em abrir uma issue.

Obrigado.

**Comment by PauloPeres** [comment]
Opa obrigado, vou dar update aqui!
