### ISSUE TITLE
URL de retorno

### ISSUE THREAD

**Issue by guztavoalves** [payu-br/bcash-magento-transparente#69]
Olá,
olhando o painel do cliente no Bcash, há uma opção de informar uma URL de retorno, é necessário informar? Caso sim, qual seria o URL?

Com o PagSeguro informamos uma URL também, mas ela é personalizada, não sei se é o mesmo caso desse módulo.

Alguém saberia dizer se é?

**Comment by danilobenedetti** [comment]
Bom dia,

O módulo possui o serviço implementado e a URL de retorno é enviada na requisição. Com isso não será necessário informar a URL no sistema do Bcash.
