### ISSUE TITLE
Erro com a versão do PHP > 5.6.14

### ISSUE THREAD

**Issue by douguiens** [payu-br/bcash-magento-transparente#70]
Olá, tudo bem?

Então, estou tentando instalar mas está dando esse erro.
Minha versão é 5.6.19 e o máximo que o modulo aceita pelo Magento Conect é o 5.6.14

Se eu instalar manualmente vai dar problema?

Não posso fazer downgrade, é quase que instalar tudo novamente.

CONNECT ERROR: Package community/Bcash_Pagamento 1.2.5: requires PHP version >= 5.3.0 and <= 5.6.14 current is: 5.6.19-1+deb.sury.org~trusty+1

Abraços!!!

**Comment by ftgouveia** [comment]
Muito provável que não ocorra erro manual. Não realizamos ainda a validação nesta versão, porém recomendo que faça o backup de sua aplicação antes de qualquer modificação. Mas em teoria não deverá dar problema.
