### ISSUE TITLE
Todos os métodos de pagamento abrem inicialmente

### ISSUE THREAD

**Issue by rodolfovs** [payu-br/bcash-magento-transparente#73]
Boa noite,

Estou testando o módulo de vocês e identifiquei o seguinte, quando a aba formas de pagamento é aberta, todos os 3 métodos de pagamento do bcash abrem, mas só o método cartão de crédito aparece selecionado. Depois que clico em algum método ele fecha os demais métodos e deixa aberto somente o método selecionado.

Seria possível começar o checkout sem o método "cartão de crédito" selecionado e com todos os métodos fechados, só abrindo eles quando clicar no respectivo radio button? Tentei alterar o /app/design/frontend/base/default/template/bcash/pagamento/form/creditcard.phtml mas não obtive sucesso.

Agradeço a ajuda de vocês.

![captura de tela 2016-11-22 as 19 59 12](https://cloud.githubusercontent.com/assets/3920814/20543723/124bdcc0-b0ee-11e6-9105-1022d991255e.jpg)

**Comment by ftgouveia** [comment]
Você pode realizar o desenvolvimento desta alteração. Atualmente vem com o cartão de crédito habilitado. Obrigado pela sugestão iremos ver se implementamos na próxima versão estável.
