### ISSUE TITLE
Estoque não retorna quando pedido é cancelado pelo Bcash

### ISSUE THREAD

**Issue by rodolfovs** [payu-br/bcash-magento-transparente#74]
Bom dia,

Estou testando o módulo em nosso ambiente de teste e identificamos que o estoque não retorna quando a transação é cancelada, independentemente se foi feita pelo botão "Cancelar com Bcash" ou quando o cancelamento é feito direto pelo painel do Bcash, acredito que seja algum erro no arquivo que trata o retorno do status cancelado no Bcash.

Algum ideia de como podemos resolver este problema?

Obrigado!

**Comment by rodolfovs** [comment]
Olá,

Mas na verdade o estoque só não retorna quando o cancelamento é feito através do retorno do Bcash, eu tenho outras formas de pagamento no site e em todos os casos quando cancela o pedido o estoque retorna normalmente.

Será que o retorno do Bcash informando transação cancelada não deveria ativar no magento este retorno do estoque?

**Comment by ftgouveia** [comment]
Poderia me descrever melhor este cenário?

**Comment by rodolfovs** [comment]
O que eu imagino que deve estar acontecendo é o seguinte, deve ter um arquivo que interpreta o retorno do API do Bcash com o termo cancelado e desta forma o sistema magento identifica este retorno e altera o status do pedido para cancelado. Eu acho que eles retorno que altera o status do pedido no magento para cancelado não está acionando o retorno do estoque.

Eu fiz um teste e cancelei um pedido feito através do módulo de vocês, mas o cancelamento padrão do magento, e o estoque voltou normalmente. Quando eu cancelo pelo painel do Bcash, e o magento pega o retorno da API, o estoque não volta e se eu cancelo pelo botão "cancelar com bcash" o magento também cancela o pedido pelo retorno da API mas o estoque não volta, acredito que o erro seja por conta do retorno do Bcash, acho que ele não está acionando a função de retorno do estoque no magento.

**Comment by rodolfovs** [comment]
Estou utilizando o SandBox do Bcash. Eu dei uma pesquisada em outros módulos de outras empresas que deram o mesmo problema no magento e o que dizem é que o problema é no retorno, um deles resolveu alterando o status para "closed" mas não sei se essa é a melhor opção.

**Comment by rodolfovs** [comment]
Olá, alguma ideia de como podemos resolver esta issue? Tentei no final de semana mas ainda não obtive sucesso.

**Comment by rodolfovs** [comment]
Uma dúvida, tem como desabilitar o retorno automático, assim eu aprovo e cancelo os pedidos no meu painel do magento?

**Comment by ftgouveia** [comment]
Rodolfo, desculpe a demora em responde-lo, conseguiu resolver teu problema? posso abrir um chamado para lhe fornecer mais detalhes sobre sua questão!

**Comment by rodolfovs** [comment]
Olá, sem problema. Na verdade identifiquei que era um erro em meu magento, mas já corrigi, o estoque está retornando quando o pedido é cancelado. 

Quando a transação é devolvida o estoque não retorna, mas acho que quando o magento aprova o pagamento o estoque não retorna mais, mesmo que o pedido seja cancelado depois. Acredito que agora esteja tudo resolvido. Obrigado pelo retorno.

**Comment by ftgouveia** [comment]
Por nada... como havia falado anteriormente o Bcash não controla o estoque, isso é controlado via plataforma! 

Mas obrigado pela interação!
