### ISSUE TITLE
Dados da transação somem do backend e do frontend

### ISSUE THREAD

**Issue by rodolfovs** [payu-br/bcash-magento-transparente#75]
Olá,

Vocês tem ideia do que pode estar ocorrendo? Eu estou ainda em fase de teste do módulo, tanto através do sandbox quando em produção e o que acontece é o seguinte, quando faço um pedido tanto no backend quanto no frontend do cliente aparecem os dados da transação, como forma de pagamento, quantidade de parcelas, código do status, descrição do status e link, até ai tudo normal. Mas depois de uns 2 ou 3 dias esses dados não aparecem mais nem no pedido no backend e nem no painel do cliente no frontend, só aparece a descrição do método de pagamento.

Tentei ver se registrou algum log de erro mas não registrou nenhum log. É normal isso?

Obrigado pela ajuda.

**Comment by rodolfovs** [comment]
Olá,

Onde ficam salvas essas informações? Em alguma tabela do banco de dados que são esvaziadas periodicamente pelo magento?

**Comment by ftgouveia** [comment]
Você esta fazendo os testes em sandbox?

**Comment by rodolfovs** [comment]
Estou fazendo em sandbox, mas fix alguns testes em produção e aconteceu a mesma coisa.

Essas informações somem depois de 2 ou 3 dias do pedido. Eu estou imaginando que tem alguma ligação com a limpeza de log do magento, mas não faz muito sentido.

**Comment by ftgouveia** [comment]
Não apagamos nada dos registro da nossa base de dados, deve ser algum problema na sua plataforma, você pode consultar também pelo nosso Banking.

**Comment by rodolfovs** [comment]
Mas nos testes que vocês fizeram não apagam essas informações? Vocês deixam habilitado limpeza de log no magento? Meu magento só apaga log, não apaga informação do banco de dados automaticamente.

Em que tabela ficam salvas essas informações?

**Comment by ftgouveia** [comment]
Na homologação do módulo, não tivemos esse tipo de problema, veja se esta com alguma rotina que esta apagando seus logs.

**Comment by rodolfovs** [comment]
Os logs sim, o magento apaga periodicamente. Mas essas informações ficam salvas no log do magento?

**Comment by ftgouveia** [comment]
As informações de transações imagino que fica armazenado no log do magento e do lado do Bcash fica armazenado em nossa base de dados, você pode consultar as transações efetuadas no Banking do sandbox. https://sandbox.bcash.com.br/login/acessar/

**Comment by rodolfovs** [comment]
No lado do bcash ficam intactas, só apagam do lado do magento. Outros métodos de pagamento que utilizamos não apagam, por isso estranhei. Vocês que definiram onde ficaria salvo essas informaçõe sno magento, ou isso é padrão?

**Comment by rodolfovs** [comment]
Você tem acesso a algum pedido feito em seus testes para verificar se essas informações apagaram? Eu não acredito que seja um problema de minha loja porque se fosse apagariam de outras formas de pagamento.

**Comment by ftgouveia** [comment]
isso é padrão... no momento não tenho como simular o seu problema. Mas na fase de testes os logs não eram apagados não, verifica a periodicidade para a limpeza dos logs

**Comment by rodolfovs** [comment]
Mas deveria ficar salvo no log essas informações? Porque log, por padrão, são apagados depois de um certo tempo, não devem ficar no sistema. Essas informações não deveriam ficar salvas em outra tabela, para quando o magento apagar os logs essa informação não ser apagada?

**Comment by ftgouveia** [comment]
Acho que essas informações também são salvas no banco de dados do magento. já verificou?

**Comment by rodolfovs** [comment]
Mas em que tabela são salvas, você sabe?

**Comment by rodolfovs** [comment]
Você tem acesso a loja teste onde testaram o plugin? Para ver se os dados da transação apagaram também?

**Comment by rodolfovs** [comment]
Eu acabei de acessar a tabela **sales_flat_order** no banco de dados e as informações estão lá, não foram apagadas, só não está aparecendo no pedido depois de alguns dias. Será que não pode ser um erro no arquivo /app/design/frontend/base/default/template/bcash/pagamento/info.phtml ?

**Comment by rodolfovs** [comment]
Eu não sei de qual tabela este arquivo **/app/design/frontend/base/default/template/bcash/pagamento/info.phtml** pega as informações, será que daria para ele pegar informação da transação através da tabela sales_flat_order? Se der acredito que resolva o problema, pois este arquivo info é somente para informar os dados, não influencia no funcionamento do módulo.

**Comment by ftgouveia** [comment]
Conseguiu resolver teu problema Rodolfo?

**Comment by rodolfovs** [comment]
Olá, ainda não. Eu não descobri de que tabela do banco de dados são tiradas as informações do arquivo  **/app/design/frontend/base/default/template/bcash/pagamento/info.phtml**. A tabela sales_flat_order contém todas as informações do pedido e lá constam todos os dados das transações, se eu conseguisse importar os dados dessa tabela já resolveria o problema, mas ainda não consegui.

Você tem alguma sugestão de como podemos resolver? Ou você conseguiu verificar em sua loja teste se esse erro ocorre também com você?

**Comment by ftgouveia** [comment]
Não ocorre, verifiquei na minha base e esta tudo OK,

**Comment by ftgouveia** [comment]
Você ja viu sobre a questão de não apagar essas informações? alguma configuração?

**Comment by rodolfovs** [comment]
na verdade como fica salvo no banco de dados, não tem ligação com a limpeza de log, eu olhei todas as tabelas de log e nenhuma consta essas informações

**Comment by rodolfovs** [comment]
você sabe qual tabela o arquivo **/app/design/frontend/base/default/template/bcash/pagamento/info.phtml** retira as informações? Porque queria ver se os dados estão na tabela, se estiverem eu sei que não te a ver com o banco de dados

**Comment by rodolfovs** [comment]
Eu acho que o problema não é na base, porque minha tabela **sales_flat_order** está tudo certo, todas as informações da transação Bcash estão lá. Acredito que possa ou ser algum problema com algum arquivo php que importa essas informações para o o painel do cliente no frontend e no backend ou essa informação é retirada de outro lugar que não a **sales_flat_order**.

**Comment by rodolfovs** [comment]
Você consultou só seu banco de dados ou verificou no magento também, dentro de algum pedido?

**Comment by ftgouveia** [comment]
Rodolfo, Tudo certo com seus testes? estou fechando a tarefa!

**Comment by rodolfovs** [comment]
Olá,

Infelizmente não deu certo, o erro persiste sem identificarmos o motivo.

**Comment by JonathanCosta** [comment]
@rodolfovs O erro ainda persiste pra você?
